### ISSUE TITLE
Why do you choose Spring Native for your app

### ISSUE THREAD

**Issue by HelloTo4x** [seguri/spring-boot-to-spring-native#1]
Hi, i am reading your project, but i have a question, why do u choose Spring Native for your app instead of Quarkus of other framework for build with GraalVM. Can u tell me the pros and cons of Spring Native ? When should we use it instead of other framewoks ?

**Comment by seguri** [comment]
Hi, the code is related to the live project "Spring Boot to Spring Native" by Manning, so I'm not choosing anything, just going through the project. You can find more information on Spring Native vs Quarkus [here](https://letmegooglethat.com/?q=spring+native+vs+quarkus).
